# Generated by Django 4.2.5 on 2023-11-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_application_status_usersapplications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersapplications',
            name='quantity',
        ),
    ]
