# Generated by Django 4.2.5 on 2023-11-20 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_usersapplications_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.applicationstatus'),
        ),
    ]
