# Generated by Django 4.2.5 on 2023-11-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_application_timestamp_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
