# Generated by Django 4.2.5 on 2023-11-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_application_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='timestamp',
            new_name='created_timestamp',
        ),
    ]
