# Generated by Django 4.2.5 on 2023-11-21 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_timestamp_application_created_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersapplications',
            name='created_timestamp',
        ),
    ]
