# Generated by Django 4.2.5 on 2023-11-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_application_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='author',
        ),
    ]
