# Generated by Django 4.2.5 on 2023-11-21 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_usersapplications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersapplications',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.applicationstatus'),
        ),
    ]
