# Generated by Django 4.2.5 on 2023-11-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_application_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='image',
            new_name='imageofapp',
        ),
    ]
